name: CI

on: push

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: latest
      - uses: actions/checkout@v2

      - name: pipeline
        run: earthly -P --ci +all

